const errorMessage = {
  FETCH_ERROR: '데이터를 불러오는데 실패했습니다.',
  INTERNAL_ERROR: '작업 도중 에러가 발생했습니다.'
};

export default errorMessage;
